### PR TITLE
Make CODAP Flow

### PR DESCRIPTION
**Pull request by stardust66**
update

Changes
- Remove update buttons
- Make created tables always update

We need to figure out what to do with errors. Currently, any errors during updates crash the plugin. We need to figure out how to present errors to the user.

### CODE REVIEW

**Comment by stardust66** [comment]
I added error handling, but the error messages are quite long.
image

**Comment by stardust66** [comment]
There's also the question of what to do on multiple errors. We need a better way to indicate errors than the one place where some error message might appear.

**Comment by thomascastleman** [comment]
Wooo! This is great. I think we should discuss what to do about errors at the next meeting, or maybe even ask Emmanuel at some point.

This looks great, and if the errors are verbose at least they give enough info to solve the problem. One thing I do notice though is if I run into an error, then fix the problem (add back in a deleted attribute, etc), the message persists, even though the tables update successfully. It would be nice to have the error get cleared somehow

**Comment by stardust66** [comment]
> if I run into an error, then fix the problem (add back in a deleted attribute, etc), the message persists, even though the tables update successfully. It would be nice to have the error get cleared somehow

The latest commit should fix this. I'm a little worried about errors overriding each other, but we can discuss that later.

**Pull request merged**
