### PR TITLE
Fill out IframePhone types and add return type annotations to API

### PR DESCRIPTION
**Pull request by P-bibs**
This PR includes a transcription of the types on [the IframePhone wiki](https://github.com/concord-consortium/codap/wiki/CODAP-Data-Interactive-Plugin-API) into Typescript interfaces so we have them for future use. It also adds return type annotations to some of the IframePhone API functions to help cut down on eslint warnings.

### CODE REVIEW

**Comment by stardust66** [comment]
Do you mind if I add a commit to this? I've written a separate function type for each of our request/response pairs

**Comment by P-bibs** [comment]
@stardust66 yep feel free to add/remove whatever you see fit

**Review by stardust66 — APPROVED** [review]
Looks good. Thanks for putting in the work to eliminate all those warnings.

**Review by thomascastleman — APPROVED** [review]

**Comment by P-bibs** [comment]
@stardust66 Can I delete this PR/branch now?

**Pull request closed without merging**
