### PR TITLE
Initialize interactive frame on startup

### PR DESCRIPTION
**Pull request by stardust66**
Nice to have: give plugin a title and make it full size on startup.

image

### CODE REVIEW

**Comment by thomascastleman** [comment]
Amazing!

**Comment by stardust66** [comment]
Of course, the dimensions are hard coded

**Comment by P-bibs** [comment]
Too bad there's nothing like `Notify: autoscale` for plugin windows

**Comment by thomascastleman** [comment]
Good to merge?

**Comment by P-bibs** [comment]
Yep :+1:

**Pull request merged**
