### PR TITLE
Fix attribute selector bugs

### LINKED ISSUE #97: Multi attribute allows duplicate attributes
In most cases, the user shouldn't be allowed to select duplicate attributes using the multi attribute selector. We should adjust the component to disallow duplicates (except maybe if a prop flag is passed in).

### PR DESCRIPTION
**Pull request by P-bibs**
Fixes #97 and #98. Also removes an extraneous UI component in `Select Attributes`.

@stardust66 I had to include hiding and unhiding attributes as mutating operations to make sure they invalidated the cache. Can you make sure I did everything right? I'm no super familiar with the caching code.

### CODE REVIEW

**Comment by thomascastleman** [comment]
If I select all possible attributes from a dataset and then hide one of them, the dropdown formerly holding the now-hidden attribute goes blank:

missing-attr

Which isn't actually terrible since the transformation goes through correctly anyway (it only groups by State, sample and Year). But it would be nice if we could eliminate this blank dropdown altogether.

**Comment by stardust66** [comment]
@P-bibs, caching looks fine.

I've got a fix for the blank dropdown, should I push it?

**Comment by P-bibs** [comment]
@stardust66 yep go for it

**Comment by stardust66** [comment]
Should be fixed now.

**Review by stardust66 — APPROVED** [review]

**Review by thomascastleman — APPROVED** [review]
Nice!

**Pull request merged**
