### PR TITLE
Update attribute selectors when attributes change (deleted or renamed)

### PR DESCRIPTION
**Pull request by stardust66**
If an attribute gets selected and then gets deleted, the attribute selector will reset. A multi attribute selector will filter out any invalid selected attributes when they change.

### CODE REVIEW

**Comment by thomascastleman** [comment]
This looks great, but I'm noticing one odd behavior: if you delete an attribute that is the last in its collection, it appears to remain in the dropdown (in the multi- and single- selects) and then will only go away once you make some change to another attribute.

Any idea why this is going on?

**Comment by stardust66** [comment]
Good catch. I'll look at it later tonight.

**Comment by stardust66** [comment]
Just rebased on top of main. The change from #51 fixes this.

**Review by thomascastleman — APPROVED** [review]
Nice, looks good

**Review by P-bibs — APPROVED** [review]
👍

**Pull request merged**
