### PR TITLE
validate attributes in a uniform way

### PR DESCRIPTION
**Pull request by thomascastleman**
This adds a mechanism for ensuring that when a transformer takes a dataset and an attribute(s) from that dataset, we can check that the attribute exists within the dataset (by searching collections).

Previously, "Invalid attribute" errors were mostly being detected when we were processing a row and found that the given attribute was `undefined` for that row. We later discovered that rows can be `undefined` for an attribute that is indeed part of the dataset (see #144 and #148). Relying on row processing to detect these errors was brittle because 1) if there are no rows, attribute errors wouldn't be detected, and 2) the above situation, in which an attribute is actually valid but `undefined` in rows.

This checks attributes separately from handling of undefined values in rows. This PR also moves to treating `row[attr] === undefined` as a _missing value_, instead of an error--this is because when this happens, it appears exactly as a missing value does to the user.

### CODE REVIEW

**Comment by thomascastleman** [comment]
Worth noting: this doesn't actually fix #148 -- it just changes the error you get. It now errors when it goes to the formula evaluator--it sees the child attribute as "unrecognized" and this is likely because it's undefined. I think the ideal behavior would be to treat the not yet defined child attribute as a missing value (as it looks), but this might involve ensuring that when we send a formula off for evaluation, all valid attributes are bound (whether to a real value or `""` for missing values).

**Comment by P-bibs** [comment]
Just to clarify: are you suggesting that before we send a formula off to be evaluated on a table, we call a function to go over that table and replace any `undefined`s with `""`s? I think this could work, and hopefully wouldn't result in too much of a performance hit.

**Comment by thomascastleman** [comment]
Yes, something like that. In effect, this would normalize missing values to `""`, even though they can appear as both `undefined` and `""`.

**Comment by thomascastleman** [comment]
This look okay? @stardust66 @P-bibs It will fix several broken tests so I'm eager to merge if possible.

**Review by P-bibs — APPROVED** [review]
Nice work! I don't think I had realized how many different places we had duplicated this functionality.

**Pull request merged**
